### ISSUE TITLE
Current favicon does not well represent NC

### ISSUE THREAD

**Issue by BenSegal** [ncph/ncph3#1]
This page needs a better favicon.

**Comment by geoffhill** [comment]
Thanks @BenSegal for giving it a go.

Here was what I think was wrong with the original:

* Background behind Cage is solid color, not transparent.
* Photo does not scale well to smaller sizes (favicons typically shown at 16x16 or 32x32).

I guess this displays an alternate, happier (?), and far more popular picture of him, but it suffers from most of the same problems.

**Comment by ncph** [comment]
Thanks @BenSegal for giving it a go.

Here was what I think was wrong with the original:

* Background behind Cage is solid color, not transparent.
* Photo does not scale well to smaller sizes (favicons typically shown at 16x16 or 32x32).

I guess this displays an alternate, happier (?), and far more popular picture of him, but it suffers from most of the same problems.

**Comment by BenSegal** [comment]
I will try this again with an image suggested by Kevin.

**Comment by ncph** [comment]
Addressed by d68f596b5. We're using a vector image source now.
