### ISSUE TITLE
Would like to see a counter to see how far you are

### ISSUE THREAD

**Issue by BenSegal** [ncph/ncph3#4]
As a watcher it is difficult to know how many full clips you have seen and how many drinks you have taken. It would be nice to add a counter on the site to tally this.

**Comment by BenSegal** [comment]
I have limited design skills so my counter will be minimalistic.

**Comment by ncph** [comment]
Here's what I expect of this implementation:

* html should include a `<button>` tag for each counter to be displayed, with a unique ID which just specifies location, e.g. `id=topleft`.

* css should position these buttons based on ID, as well as define a common style for `<button>` elements. The buttons should be **round** with text centered in both direction. They should have ~80% opacity and a drop shadow.

* js should add a function `updateCounter()` which is called in the place `vidCounter` is incremented now, which does the increment and also updates the HTML.

**Comment by BenSegal** [comment]
Thanks. This will be helpful.

**Comment by ncph** [comment]
More tips:

* The magical JS incantation to set the contents of an element is:

```
document.getElementById('topleft').innerHTML = '...';
```

* Look up the Material Design FAB (floating action button). I imagine that it should look something like that, so look for examples which try to replicate that style in basic CSS.

**Comment by ncph** [comment]
This was added in 93e0ad1, abae8f8 and 16ce9c9.
