### ISSUE TITLE
Feedback on the volume manipulation

### ISSUE THREAD

**Issue by BenSegal** [ncph/ncph3#5]
It would be nice to have some feedback when you use the hotkeys to manipulate the volume. Specifically a bar or some numbers saying where you are at with the volume.

**Comment by kevinshepherd** [comment]
I'd actually consider removing volume manipulation altogether; now that we have volume normalization across all clips this feature seems unnecessary. especially given the normal use case for the ncph, turning it to listen to other things is not really an intended behavior. 
plus, it's always nice to keep this feature-light. plus plus, there's nothing to indicate to a new user that arrow keys will even do anything -- that's not a normal/intuitive mapping -- so we'd have to indicate that these other controls exist somehow, which is more clutter on the main page.

**Comment by BenSegal** [comment]
If the plan is to completely remove volume manipulation I will close this issue.
